
# Name your project! Project names should contain only lowercase characters
# and underscores_A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_multiple_projects'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_longle'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory_You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view_This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform_
# The configuration below will override this setting for models in the example folder to 
# instead be +materialized as tables_Any models you add to the root of the models folder will 
# continue to be built as views_These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  dbt_multiple_projects:
    brazillian_ecom:
      staging:
        +materialized: view
        operations:
          +tags: 'be_ops'
        marketing:
          +tags: 'be_mkt'
      intermediate:
        +materialized: ephemeral
        finance:
          +tags: 'be_fin'
      mart:
        +materialized: table
        +docs:
          node_color: '#7D3C98'
        operations:
          +schema: operations
          +tags: 'be_ops'
        marketing:
          +schema: marketing
          +tags: 'be_mkt'
        finance:
          +schema: finance
          +tags: 'be_fin'

    anom_ecom:
      staging:
        +materialized: view
      intermediate:
        +materialized: ephemeral
      mart:
        +materialized: table

    utilities:
      +materialized: table
      intermediate:
        +materialized: ephemeral

    seed:
      -name: exchange_rate_real_to_usd
      config:
        schema: seed_data
        +materialized: ephemeral
