
dbt_longle:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: spheric-radio-397503
      dataset: brazillian_ecom_dbt
      threads: 4
      # These fields come from the service account json keyfile
      keyfile_json:
        type: service_account
        project_id: spheric-radio-397503
        private_key_id: c8d5078c19e1b48d2d86d36151730eb0d96c26f7
        private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCggJ+WnfcTDp/M\nXerOvUfA1tlYOmJhRe1JpkeVyUXuyv5FRJR1iQON1QE30OD0t1aD21v42FiF4SUl\nw84YmXjs/9vu+jlP8Zl7vQETR8IMvDNqm0QNOyPvZPrHiBEMlynYS4OmiFxABob9\nekIjwmBug+Lj6BZOtgFVoLF0EBN0DdANt03uODObYA9ucW4oV5dWDXjfqLfLDu45\na9V7IYShJN+V2QwFT5BFOXlu3OOboWJxeOVm7OrLweKFDakUGvqUIsI2zBYHWk6X\n6wB9bkl3sMcB04sHRImzVa0x9PX6cWuvt9vfskW6lvDKSuc1RPoeQoUOJxSrBLiV\naOdwXNDDAgMBAAECggEAJdNKSP+/W8FljY9QqBpZj6vSmwVfbBdDvcivNDC0B3vV\ngtOPvUdmDAX3/ISAj4upmveWbEXoTtzpmUXVC10X75q45VAZM6r3hf7cAwQ1SjUM\nVQJ0fj3C0UdWBrIden8hgHUDeLrIKtqe85vdfHnxqfnw/c8TesdP9zMgvv6O5xl+\naGPQNSl5PkIkLFR67URcaTz1RrF5coX9tGwP4JnXQwZ+9DBih9kOd8oCfxkPursZ\nH+PVV1vU5iwZCL/flPPwayJux3un223fVR9/BkOaUCxsZOVAUu0XT5aZH+5PYJ9D\nTEzyj5o0huDDx17m33Dp2TmEUSnJlZpFHu/oL9DuKQKBgQDbXxjTrtKi+QotbOaM\neqnkbctv5tub2NrN1iSAQaR15oACRc/Bmw1r17GLO2gEo7XJMMvWRXKwag1owVqq\nkkg41Mtj1KWlMe1xjwj8UKYXezfDymH8GJpbwGtcPV0eHVttZPwL1NYLHyjpOjNo\ndYXusBvJzF/TiiQs9RKIeD3VPQKBgQC7TTRWmGjS0oMxC0tYdWsbJ1pGkfUznXtY\nYz/WCLaO7AIZUbRqQG4YBApFZmYOSxiimeIP21zR4GdmE3FaFikOcD+EzjYqLF2E\n2yfLXCjNEKpUhyiKxN9ZFQtr0I1QIe14CsiPo8BdQ5PosrSfHTuEhkdCVNq3sviZ\nqW/DAOud/wKBgFmjGwbsKX+UWVdEZ1RBjwga4QTBhTzCOG3hMZsCt4vBes7y7biD\nfdFyGkb1KES1DEPAX5oXWIzDWOVUFJMcIMywDselDWZZ51b+hkJrReLUY23qVW1o\nNDKHhpbzMAhtIH2rxN2kwy1aNyJNuNHXK7njVgd4LjPG/48rOL5wu3tVAoGAcpYy\n9N9dEc1UEYcVW1LKadxTcGUPG7q2oUZm4WyHMzzTs+W2eGJeeDbQidCxkwECW0fF\nc2oCiSu+VkaCzFhOWdT2Jyt5G6f0trjUyabiF0Kg0gG2Hd9/vKIRUK5QJbv76bq/\nJJFLuEMFlBDwS3+4z8TOh5geDtBhIrDz/NrtSsUCgYEAwf/uSthrSTXWYW84t9hX\n6LshIvy2F32aJGOrnzlni1LKJVInsRm1z2e6YIbWKPBkivA3cLsjzMh6HcTS0F6+\naaWOXbSSAyqM8SqWDnwpdyo8eCw6C1BpbjVAPSwBtCi4yBnkrxdKvhuw5tseQ4sl\nrkNjp9PoU50cW/yMn/7+IUo=\n-----END PRIVATE KEY-----\n"
        client_email: brazil-ecom@spheric-radio-397503.iam.gserviceaccount.com
        client_id: 113686886764435785138
        auth_uri: https://accounts.google.com/o/oauth2/auth
        token_uri: https://oauth2.googleapis.com/token
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/brazil-ecom%40spheric-radio-397503.iam.gserviceaccount.com