# # sources.yml

# version: 2

# sources:
#   - name: brazillian_ecom  # Corrected source name
#     database: spheric-radio-397503
#     tables:
#       - name: order_items
#       - name: customers
#       - name: order_payments
#       - name: orders_dataset
#       - name: product_category_name_translation
#       - name: products_dataset
#       - name: sellers
#       - name: data_geo
#       - name: geolocation
#       - name: order_reviews
#       - name: closed_deals_dataset
#       - name: marketing_qualified_leads_dataset
